server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: schedule
          uri: http://localhost:8081
          predicates:
            - Path=/schedules/** 
        - id: Review
          uri: http://localhost:8082
          predicates:
            - Path=/reviews/** 
        - id: Viewpage
          uri: http://localhost:8083
          predicates:
            - Path= 
        - id: Message
          uri: http://localhost:8084
          predicates:
            - Path=/messages/** 
        - id: Communication
          uri: http://localhost:8085
          predicates:
            - Path=/communications/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: schedule
          uri: http://schedule:8080
          predicates:
            - Path=/schedules/** 
        - id: Review
          uri: http://review:8080
          predicates:
            - Path=/reviews/** 
        - id: Viewpage
          uri: http://viewpage:8080
          predicates:
            - Path= 
        - id: Message
          uri: http://message:8080
          predicates:
            - Path=/messages/** 
        - id: Communication
          uri: http://communication:8080
          predicates:
            - Path=/communications/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
