---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule
  labels:
    app: schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule
  template:
    metadata:
      labels:
        app: schedule
    spec:
      containers:
        - name: schedule
          image: username/schedule:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Review
  labels:
    app: Review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Review
  template:
    metadata:
      labels:
        app: Review
    spec:
      containers:
        - name: Review
          image: username/Review:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Viewpage
  labels:
    app: Viewpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Viewpage
  template:
    metadata:
      labels:
        app: Viewpage
    spec:
      containers:
        - name: Viewpage
          image: username/Viewpage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Message
  labels:
    app: Message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Message
  template:
    metadata:
      labels:
        app: Message
    spec:
      containers:
        - name: Message
          image: username/Message:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Communication
  labels:
    app: Communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Communication
  template:
    metadata:
      labels:
        app: Communication
    spec:
      containers:
        - name: Communication
          image: username/Communication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: schedule
  labels:
    app: schedule
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: schedule


---


apiVersion: v1
kind: Service
metadata:
  name: Review
  labels:
    app: Review
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Review


---


apiVersion: v1
kind: Service
metadata:
  name: Viewpage
  labels:
    app: Viewpage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Viewpage


---


apiVersion: v1
kind: Service
metadata:
  name: Message
  labels:
    app: Message
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Message


---


apiVersion: v1
kind: Service
metadata:
  name: Communication
  labels:
    app: Communication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Communication

